-- 简历优化提案表（P2-1）：Agent 生成的 Patch 提案持久化（HITL 审计追溯）
-- patches 整体 JSON 存储：apply 时整体读取校验，无逐条查询需求
-- 状态机：PENDING（待用户决策）→ APPLIED（已应用） / REJECTED（用户拒绝）

CREATE TABLE resume_optimization_proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id BIGINT NOT NULL,
  source_version_id BIGINT NOT NULL,
  optimization_type VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  summary TEXT,
  patches_json TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  decided_at TIMESTAMP(6),
  CONSTRAINT resume_optimization_proposals_status_check
    CHECK (status IN ('PENDING', 'APPLIED', 'REJECTED')),
  CONSTRAINT resume_optimization_proposals_type_check
    CHECK (optimization_type IN ('GENERAL', 'TARGET_DIRECTION', 'JD_TARGETED')),
  CONSTRAINT fk_resume_optimization_proposals_resume
    FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE
);

CREATE INDEX idx_resume_optimization_proposal_resume
  ON resume_optimization_proposals (resume_id, created_at DESC);
