-- Copilot 对话持久化：会话与消息表
-- 参考 rag_chat_sessions / rag_chat_messages 结构，去掉知识库绑定，消息增加 blocks JSON 列

CREATE TABLE agent_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  user_id VARCHAR(64) NOT NULL DEFAULT 'default',
  message_count INTEGER NOT NULL DEFAULT 0,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT agent_conversations_status_check CHECK (status IN ('ACTIVE','ARCHIVED'))
);

CREATE TABLE agent_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  blocks TEXT,
  message_order INTEGER NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT agent_messages_role_check CHECK (role IN ('USER','ASSISTANT')),
  CONSTRAINT fk_agent_messages_conversation
    FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id)
);

CREATE INDEX idx_agent_message_order ON agent_messages (conversation_id, message_order);
CREATE INDEX idx_agent_conversation_updated ON agent_conversations (updated_at);