-- P4-9a：逐轮提交幂等与会话推进一致性。
--
-- 背景（此前真实缺陷）：
--   1. submitAnswer / skip 只校验「index 落在题库范围内」，不校验它**是不是当前待答题**，
--      也不看会话是否已结束 → 重复提交、并发提交、晚到的请求都会各自独立推进一次
--      （同一题被答两遍、索引回退、已 COMPLETED 的会话被写回 IN_PROGRESS）。
--   2. 一轮推进被拆成 3 个独立事务（答案 / 索引 / 状态），中间失败会留下半状态。
--   3. 幂等只覆盖「创建面试」，逐轮提交没有请求标识，重试只能靠用户手速。
--
-- 本迁移提供两样东西：
--   turn_version    会话推进版本。每次成功推进（作答 / 跳过 / 结束）+1，
--                   与请求标识一起构成乐观并发控制；条件更新影响 0 行即代表会话已被
--                   其他请求推进，晚到的模型结果因此无法回退或重开会话。
--   evaluate_epoch  评估任务代次。每次请求评估 +1，随 Stream 消息一起投递；
--                   消费端只会执行「不低于当前代次」的消息，避免重复触发产生第二份业务效果。
ALTER TABLE interview_sessions
    ADD COLUMN turn_version INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN evaluate_epoch BIGINT NOT NULL DEFAULT 0;

COMMENT ON COLUMN interview_sessions.turn_version IS
    '会话推进版本（P4-9a）：作答/跳过/结束各 +1，用于逐轮提交的乐观并发控制';
COMMENT ON COLUMN interview_sessions.evaluate_epoch IS
    '评估任务代次（P4-9a）：每次请求评估 +1，消费端据此丢弃过期触发';

-- 逐轮请求记录：请求标识 → 原结果。
--
-- 作用有三：
--   1. 已处理请求重放时**返回原结果**，不再次推进、不重复花模型调用；
--   2. 同一标识携带不同载荷（题目索引 / 作答内容 / 动作变了）→ 明确拒绝，而不是静默改写历史；
--   3. 唯一索引 (session_id, request_id) 是并发重复提交的最后一道闸门：
--      两个请求同时提交同一标识时，只有先提交的那个能落库，另一个必然冲突。
CREATE TABLE interview_turn_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    action VARCHAR(16) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    base_version INTEGER NOT NULL,
    result_version INTEGER NOT NULL,
    response_json TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_interview_turn_request UNIQUE (session_id, request_id),
    CONSTRAINT interview_turn_requests_action_check
        CHECK (action IN ('ANSWER', 'SKIP', 'COMPLETE')),
    CONSTRAINT fk_interview_turn_request_session
        FOREIGN KEY (session_id) REFERENCES interview_sessions (session_id) ON DELETE CASCADE
);

COMMENT ON TABLE interview_turn_requests IS
    '逐轮提交幂等记录（P4-9a）：请求标识 + 载荷指纹 + 原结果，重放返回原结果而非再次推进';

-- 会话删除时按 session_id 级联清理（外键已带 ON DELETE CASCADE），
-- 这里补一个按时间倒序的索引，便于排查「最近一次推进是谁提交的」。
CREATE INDEX idx_interview_turn_request_session_created
    ON interview_turn_requests (session_id, created_at DESC);
