-- 简历版本表（P2-0 简历优化地基）：原始导入与 AI 优化产物都以版本存储，原版本永不覆盖
-- contentJson 为结构化 Resume JSON（basicInfo/education/experience/projects/skills/customSections）
-- 约束：本单用户项目不设 user_id（与 resumes 表一致）

CREATE TABLE resume_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id BIGINT NOT NULL,
  version INTEGER NOT NULL,
  source_version_id BIGINT,
  optimization_type VARCHAR(32),
  target_job_id BIGINT,
  content_json TEXT NOT NULL,
  source VARCHAR(32) NOT NULL,
  confirmation_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_CONFIRMATION',
  missing_fields_json TEXT,
  source_created_at TIMESTAMP(6) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT resume_versions_source_check
    CHECK (source IN ('IMPORT', 'USER_EDIT', 'AI_OPTIMIZE')),
  CONSTRAINT resume_versions_confirmation_status_check
    CHECK (confirmation_status IN ('PENDING_CONFIRMATION', 'ACTIVE', 'NEED_USER_INFO')),
  CONSTRAINT fk_resume_versions_resume
    FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
  CONSTRAINT uk_resume_version UNIQUE (resume_id, version)
);

CREATE INDEX idx_resume_version_resume ON resume_versions (resume_id, version DESC);
