-- 长期用户能力画像（P3-1）：Evidence-driven Skill Profile
-- skill_profiles：聚合后的技能分（Core-4 §Profile Aggregator：skill/score/evidenceCount/updatedAt）
-- skill_evidence：可追溯证据（sourceType 限定 Resume / Interview Session / Interview Turn）
-- 约束：本单用户项目 user_id 恒为 'default'，仅作架构预留（同 agent_conversations）

CREATE TABLE skill_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL DEFAULT 'default',
  skill VARCHAR(128) NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  evidence_count INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_skill_profile UNIQUE (user_id, skill)
);

CREATE TABLE skill_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL DEFAULT 'default',
  skill VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  score INTEGER NOT NULL,
  occurred_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT skill_evidence_source_type_check
    CHECK (source_type IN ('RESUME', 'INTERVIEW_SESSION', 'INTERVIEW_TURN')),
  -- 同一来源同一技能只保留一条证据：评估任务重放 / 重复消费时幂等
  CONSTRAINT uk_skill_evidence UNIQUE (user_id, skill, source_type, source_id)
);

CREATE INDEX idx_skill_evidence_skill ON skill_evidence (user_id, skill);
CREATE INDEX idx_skill_evidence_source ON skill_evidence (source_type, source_id);
